import { Archivo } from "next/font/google";
import "./globals.css";

const archivo = Archivo({subsets: ["latin"]});

export const metadata = {
  title: "Logoipsum",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${archivo.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
